trace-forwarder: Provide hint on error
If agent tracing is enabled but the trace forwarder is not running, the
agent will fail with a message stating the forwarder needs to be
running.

Add a similar message to the forwarder which also will fail unless an
openTelemetry collector (such as Jaeger) is running on the host. Note
that in this scenario, although the trace forwarder will die, the agent
will continue to run (since the forwarder _was_ running when the agent
started) but will generate errors such as:

```
  ERROR: failed to write span: Custom { kind: Other, error: "failed to write trace header: Os { code: 32, kind: BrokenPipe, message: \"Broken pipe\" }" }
```

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>